### ISSUE TITLE
Hello I have an issue with this repository

### ISSUE THREAD

**Issue by Loptt** [pcruiher08/Mathematics#1]
Hello I think it is not working for me. I try installing it and it says 
``You are not pcruiher08 you are not enough NP for this mathematical model ``
Please help asap

**Comment by pcruiher08** [comment]
Send a picture of your credit card from both sides to my email <pcruiher089@gmail.com>. I'll be glad to send you the full mathematical model once I receive that email.

**Comment by Loptt** [comment]
`DANKESCHON`
